import './globals.css';
import { Inter } from 'next/font/google';
import CommonLayout from '../Components/CommonLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Movie app',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <CommonLayout>{children}</CommonLayout>
      </body>
    </html>
  );
}
